### ISSUE TITLE
auto stop if user do not speed fro few seconds, speech translation 

### ISSUE THREAD

**Issue by asar-s** [ClearCut3000/SpeechToDo#2]
is there is a way to stop the recoding if user do not speak for few seconds in speech translation 
platform = IOS swift

**Comment by ClearCut3000** [comment]
To stop recording if the user does not speak for a few seconds in a speech recognition platform on IOS Swift, you can use an audio buffer and set a timer. If the user stops speaking for a certain amount of time, the recording will stop.

To do this, you can use the AVAudioRecorderDelegate methods, which allow you to track events related to audio recording. You can create a timer using the Timer method from Foundation and set it for a certain number of seconds. When the timer expires, you can call a method that will stop the audio recording.

For example, you can create a timer variable:
`var recordingTimer: Timer?`
Then, when the recording starts, you can start the timer:
```
recordingTimer = Timer.scheduledTimer(withTimeInterval: 5, repeats: false, block: { [weak self] _ in
    self?.stopRecording()
})
```
In this example, the timer is set for 5 seconds and after that time expires, it calls the stopRecording() method, which stops the audio recording.

If the user starts speaking again, the timer can be reset and started again:
```
recordingTimer?.invalidate()
recordingTimer = nil
recordingTimer = Timer.scheduledTimer(withTimeInterval: 5, repeats: false, block: { [weak self] _ in
    self?.stopRecording()
})
```
In this way, the app can stop recording if the user stops speaking for a certain amount of time and resume recording if the user starts speaking again.

To implement a similar approach of stopping recording if the user does not speak for a few seconds in the SpeechManager class, you can add a timer that will stop recording if no audio is detected within a specified time interval. Here's an example of how you can modify the startRecording() function:
```
`func startRecording(completion: @escaping (String?) -> Void) {
    ...
    let recordingTimeout: TimeInterval = 5 // set the recording timeout to 5 seconds
    var recordingTimer: Timer?

    recognitionRequest = SFSpeechAudioBufferRecognitionRequest()
    recognizer.recognitionTask(with: recognitionRequest!) { result, error in
      ...
    }

    audioEngine = AVAudioEngine()
    inputNode = audioEngine.inputNode
    let recordingFormat = inputNode.outputFormat(forBus: 0)
    inputNode.installTap(onBus: 0, bufferSize: 1024, format: recordingFormat) { [unowned self] (buffer, _) in
      self.recognitionRequest?.append(buffer)
      if recordingTimer == nil {
        // Start the timer if no audio has been detected yet
        recordingTimer = Timer.scheduledTimer(withTimeInterval: recordingTimeout, repeats: false) { _ in
          self.stopRecording()
          completion(nil)
        }
      } else {
        // Reset the timer if audio is still being detected
        recordingTimer?.invalidate()
        recordingTimer = Timer.scheduledTimer(withTimeInterval: recordingTimeout, repeats: false) { _ in
          self.stopRecording()
          completion(nil)
        }
      }
    }

    audioEngine.prepare()
    do {
      audioSession = AVAudioSession.sharedInstance()
      try audioSession.setCategory(.record, mode: .spokenAudio, options: .duckOthers)
      try audioSession.setActive(true, options: .notifyOthersOnDeactivation)
      try audioEngine.start()
    } catch let error {
      print("There was a problem starting recording: \(error.localizedDescription)")
    }
  }
`
```
